use_frameworks!

platform :ios, '8.0'

target 'TDTimePicker_Example' do
  pod 'TDTimePicker', :path => '../'

  target 'TDTimePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
